In [7]:
from bs4 import BeautifulSoup
import requests

In [23]:
url = 'https://pokemondb.net/pokedex/all'
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')

In [78]:
headers = soup.find_all('th')
header_text = [th.text.strip() for th in headers]

In [68]:
import pandas as pd

In [79]:
df = pd.DataFrame(columns = header_text)
df

Empty DataFrame
Columns: [#, Name, Type, Total, HP, Attack, Defense, Sp. Atk, Sp. Def, Speed]
Index: []

In [80]:
column_data = soup.find_all('tr')

In [81]:
for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]
    
    length = len(df)
    df.loc[length] = individual_row_data

In [82]:
df

,#,Name,Type,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,0001,Bulbasaur,Grass Poison,318,45,49,49,65,65,45
1,0002,Ivysaur,Grass Poison,405,60,62,63,80,80,60
2,0003,Venusaur,Grass Poison,525,80,82,83,100,100,80
3,0003,Venusaur Mega Venusaur,Grass Poison,625,80,100,123,122,120,80
4,0004,Charmander,Fire,309,39,52,43,60,50,65
...,...,...,...,...,...,...,...,...,...,...
1214,1023,Iron Crown,Steel Psychic,590,90,72,100,122,108,98
1215,1024,Terapagos Normal Form,Normal,450,90,65,85,65,85,60
1216,1024,Terapagos Terastal Form,Normal,600,95,95,110,105,110,85
1217,1024,Terapagos Stellar Form,Normal,700,160,105,110,130,110,85
1218,1025,Pecharunt,Poison Ghost,600,88,88,160,88,88,88

In [83]:
df.to_csv(r'C:\Users\subze\pokedexProject\pokedexScraper\pokedexData.csv', index = False)